export const Pahts = {
   indormation: 'about',
   structure: 'structure',
   doc: 'documents',
   admin: 'admin',
   postingspost: 'post',
   note: 'note',
   hrental: 'rent',
   news: 'new',
   onepostpage: 'postpage',
   Aevents: 'events',
   project: 'project',
   nko: 'nko',
   contacts: 'contacts',
   oneproject: 'oneproject',
   onenko: 'onenko',
   evnentsfull: "eventsfull",
   onepostevents: 'eventsone',
   eventsred: "adminevents"
}